import = ["~/.config/alacritty/themes/themes/github_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "GeistMono Nerd Font Mono"
size = 16

[shell]
program = "/opt/homebrew/bin/tmux"
args = []
