import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 16
decorations = "buttonless"
opacity = 0.66
blur = true
option_as_alt = "Both"

[font]
normal.family = "GeistMono Nerd Font Mono"
normal.style = "Regular"
bold.family = "GeistMono Nerd Font Mono"
bold.style = "Bold"
size = 16

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]
